insert into exercises (body_part, link, name, position) VALUES (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Wyciskanie sztangi sprzed głowy"	,	"1"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Wyciskanie sztangi zza głowy"	,	"2"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Wyciskanie sztangielek"	,	"3"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Arnoldki"	,	"4"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie sztangielek bokiem w górę"	,	"5"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie sztangielek w opadzie tułowia"	,	"6"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Podciąganie sztangi wzdłuż tułowia"	,	"7"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Podciąganie sztangielek wzdłuż tułowia"	,	"8"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie ramion w przód ze sztangą"	,	"9"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie ramion w przód ze sztangielkami"	,	"10"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie ramion ze sztangielkami w leżeniu"	,	"11"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie ramion w przód z linkami wyciągu"	,	"12"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie ramion bokiem w górę z linkami wyciągu"	,	"13"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Unoszenie ramion bokiem w górę w opadzie tułowia z linkami wyciągu"	,	"14"	),
                                                               (	"mięśnie naramienne"	,	"https://www.kulturystyka.pl/atlas/naramienne.asp"	,	"Odwrotne rozpiętki"	,	"15"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskanie sztangi w leżeniu na ławce poziomej"	,	"1"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskanie sztangielek w leżeniu na ławce poziomej"	,	"2"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskanie sztangi w leżeniu na ławce skośnej-głową w górę"	,	"3"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskanie sztangielek w leżeniu na ławce skośnej-głową w górę"	,	"4"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskanie sztangi w leżeniu na ławce skośnej-głową w dół"	,	"5"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskanie sztangielek w leżeniu na ławce skośnej-głową w dół"	,	"6"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Rozpiętki ze sztangielkami w leżeniu na ławce poziomej"	,	"7"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Rozpiętki ze sztangielkami w leżeniu na ławce skośnej -głową do góry"	,	"8"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskanie sztangi w leżeniu na ławce poziomej wąskim uchwytem"	,	"9"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Przenoszenie sztangielki w leżeniu w poprzek ławki poziomej"	,	"10"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Pompki na poręczach"	,	"11"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Rozpiętki w siadzie na maszynie"	,	"12"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Krzyżowanie linek wyciągu w staniu"	,	"13"	),
                                                               (	"klatka piersiowa"	,	"https://www.kulturystyka.pl/atlas/klatka.asp"	,	"Wyciskania poziome w siadzie na maszynie"	,	"14"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Podciąganie na drążku szerokim uchwytem (nachwyt)"	,	"1"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Podciąganie na drążku w uchwycie neutralnym"	,	"2"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Podciąganie na drążku podchwytem"	,	"3"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Podciąganie sztangi w opadzie (wiosłowanie)"	,	"4"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Podciąganie sztangielki w opadzie (wiosłowanie)"	,	"5"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Podciąganie końca sztangi w opadzie"	,	"6"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Przyciąganie linki wyciągu dolnego w siadzie płaskim"	,	"7"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Przyciąganie linki wyciągu górnego w siadzie"	,	"8"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Ściąganie drążka/rączki wyciągu górnego w siadzie szerokim uchwytem (nachwyt)"	,	"9"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Ściąganie drążka/rączki wyciągu górnego w siadzie podchwytem"	,	"10"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Ściąganie drążka/rączki wyciągu górnego w siadzie uchwyt neutralny"	,	"11"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Przenoszenie sztangi w leżeniu na ławce poziomej"	,	"12"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Podciąganie (wiosłowanie) w leżeniu na ławeczce poziomej"	,	"13"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Skłony ze sztangą trzymaną na karku tzw. dzień dobry"	,	"14"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Unoszenie tułowia z opadu"	,	"15"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Martwy ciąg"	,	"16"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Martwy ciąg na prostych nogach"	,	"17"	),
                                                               (	"mięśnie grzbietu"	,	"https://www.kulturystyka.pl/atlas/plecy.asp"	,	"Wznosy barków Szrugsy"	,	"18"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Przysiady ze sztangą na barkach"	,	"1"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Przysiady ze sztangą trzymaną z przodu"	,	"2"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Hack-przysiady"	,	"3"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Przysiady na suwnicy skośnej (hack-maszynie)"	,	"4"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Syzyfki"	,	"5"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Prostowanie nóg w siadzie"	,	"6"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Wypychanie ciężaru na suwnicy (maszynie)"	,	"7"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Uginanie nóg w leżeniu"	,	"8"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Przysiady wykroczne"	,	"9"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Nożyce"	,	"10"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Wysoki step ze sztangą/sztangielkami"	,	"11"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Odwodzenie nogi w tył"	,	"12"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Ściąganie kolan w siadzie"	,	"13"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Przywodzenie nóg do wewnątrz"	,	"14"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Odwodzenie nóg na zewnątrz"	,	"15"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Martwy ciąg na prostych nogach"	,	"16"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Wspięcia na palce w staniu"	,	"l1"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Wspięcia na palce w siadzie"	,	"l2"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Ośle wspięcia"	,	"l3"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Wspięcia na palce na hack-maszynie"	,	"l4"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Wypychanie ciężaru na maszynie/suwnicy palcami nóg"	,	"l5"	),
                                                               (	"mięśnie nóg"	,	"https://www.kulturystyka.pl/atlas/nogi.asp"	,	"Odwrotne wspięcia w staniu"	,	"l6"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skłony w leżeniu płasko"	,	"1"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skłony w leżeniu głową w dół"	,	"2"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Unoszenie nóg w leżeniu na skośnej ławce"	,	"3"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Unoszenie nóg w zwisie na drążku"	,	"4"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Unoszenie nóg w podporze"	,	"5"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Spinanie/Unoszenie kolan w leżeniu płasko"	,	"6"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skłony tułowia z linką wyciągu siedząc"	,	"7"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skręty tułowia"	,	"8"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skłony tułowia z linką wyciągu klęcząc"	,	"9"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skłony boczne"	,	"10"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skłony boczne na ławce"	,	"11"	),
                                                               (	"mięśnie brzucha"	,	"https://www.kulturystyka.pl/atlas/brzuch.asp"	,	"Skręty tułowia w leżeniu"	,	"12"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion ze sztangą stojąc podchwytem"	,	"1"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion ze sztangielkami stojąc podchwytem (z supinacją nadgarstka)"	,	"2"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion ze sztangielkami stojąc (uchwyt młotkowy)"	,	"3"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion ze sztangą na modlitewniku"	,	"4"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramienia ze sztangielką na modlitewniku"	,	"5"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion ze sztangielkami w siadzie na ławce skośnej (z supinacją nadgarstka)"	,	"6"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramienia ze sztangielką w siadzie - w podporze o kolano"	,	"7"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion podchwytem stojąc-z rączką wyciągu"	,	"8"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion ze sztangą nachwytem stojąc"	,	"9"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie ramion ze sztangą nachwytem na modlitewniku"	,	"10"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie nadgarstków podchwytem w siadzie"	,	"11"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Uginanie nadgarstków nachwytem w siadzie"	,	"12"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Prostowanie ramion na wyciągu stojąc"	,	"t1"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Wyciskanie francuskie sztangi w siadzie"	,	"t2"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Wyciskanie francuskie jednorącz sztangielki w siadzie"	,	"t3"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Wyciskanie francuskie sztangi w leżeniu"	,	"t4"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Wyciskanie francuskie sztangielki w leżeniu"	,	"t5"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Prostowanie ramienia ze sztangielką w opadzie tułowia"	,	"t6"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Prostowanie ramion na wyciągu w płaszczyźnie poziomej stojąc"	,	"t7"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Prostowanie ramion na wyciągu w płaszczyźnie poziomej w podporze"	,	"t8"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Pompki na poręczach"	,	"t9"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Pompki w podporze tyłem"	,	"t10"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Prostowanie ramienia podchwytem na wyciągu stojąc"	,	"t11"	),
                                                               (	"mięśnie ramion"	,	"https://www.kulturystyka.pl/atlas/ramiona.asp"	,	"Wyciskanie w leżeniu na ławce poziomej wąskim uchwytem"	,	"t12"	);



insert into plans (description, name) VALUES (	"Trening całego ciała na każdej jednostce treningowej"	,	"Full Body Workout"	),
                                             (	"Trening poszczególnych partii ciała na jednostce treningowej"	,	"Split"	),
                                             (	"Obwodowy siłowo-aerobowy trening całego ciała "	,	"Aerobic Circuit Training"	),
                                             (	"Podział na treningi, na których wykonuje się ćwiczenia pchane lub ciągnące "	,	"Push – Pull"	);

insert into goals (break_range, name, rep_range) VALUES (	"2-3"	,	"Masa"	,	"8-12"	),
                                                        (	"3-5"	,	"Siła"	,	"6-8"	),
                                                        (	"0.5-1"	,	"Rzeźba"	,	"12-15"	);

insert into units (set_range, units_per_week) VALUES (	"9-12"	,	1	),
                                                     (	"5-6"	,	2	),
                                                     (	"3-4"	,	3	);