insert into workouts (name, goal_id, plan_id, unit_id) VALUES (	"Trening A"	,	1	,	1	,	2	),
                                                              (	"Trening B"	,	2	,	2	,	3	),
                                                              (	"Trening C"	,	3	,	3	,	2	),
                                                              (	"Trening D"	,	1	,	4	,	3	);

insert into workouts_exercises (exercise_id, workout_id) values (	48	,	1	),
                                                                (	45	,	1	),
                                                                (	16	,	1	),
                                                                (	1	,	1	),
                                                                (	95	,	1	),
                                                                (	82	,	1	),
                                                                (	73	,	1	),
                                                                (	17	,	2	),
                                                                (	18	,	2	),
                                                                (	27	,	2	),
                                                                (	22	,	2	),
                                                                (	82	,	2	),
                                                                (	84	,	2	),
                                                                (	89	,	2	),
                                                                (	48	,	3	),
                                                                (	45	,	3	),
                                                                (	1	,	3	),
                                                                (	32	,	3	),
                                                                (	26	,	3	),
                                                                (	73	,	3	),
                                                                (	48	,	4	),
                                                                (	54	,	4	),
                                                                (	42	,	4	),
                                                                (	45	,	4	),
                                                                (	30	,	4	),
                                                                (	82	,	4	);